# # =========================
# # VPC NETWORK
# # =========================
# resource "google_compute_network" "vpc_network" {
#   name                    = "terraform-vpc"
#   auto_create_subnetworks = false
# }


# # =========================
# # SUBNETWORK
# # =========================
# resource "google_compute_subnetwork" "subnet" {
#   name          = "terraform-subnet"
#   ip_cidr_range = "10.0.0.0/24"
#   region        = "europe-west1"
#   network       = google_compute_network.vpc_network.id
# }

# # =========================
# # FIREWALL RULE
# # =========================
# resource "google_compute_firewall" "allow_ssh_http" {
#   name    = "allow-ssh-http"
#   network = google_compute_network.vpc_network.name

#   allow {
#     protocol = "tcp"
#     ports    = ["22", "80"]
#   }

#   source_ranges = ["0.0.0.0/0"]
# }


# =========================
# COMPUTE ENGINE VM
# =========================
resource "google_compute_instance" "vm_instance" {
  name         = "terraform-vm"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 10
    }
  }

  network_interface {
    network    = "default"
    # subnetwork = google_compute_subnetwork.subnet.id

    # IP publique
    access_config {}
  }

  tags = ["web"]


  # =========================
  # Provisioner: install Nginx
  # =========================
  provisioner "remote-exec" {
    # List of shell commands to run on the VM after creation
    inline = [
      # Update the package lists
      "sudo apt-get update",
      # Install Nginx web server
      "sudo apt-get install -y nginx",
      # Enable Nginx service at boot
      "sudo systemctl enable nginx",
      # Start Nginx service immediately
      "sudo systemctl start nginx"
    ]

    # Connection block: tells Terraform how to SSH into the VM
    connection {
      # SSH connection type
      type        = "ssh"
      # SSH username on the VM (from your cloud_user / gcloud login)
      user        = "boris"
      # Path to the private SSH key generated by gcloud
      private_key = file("C:\\Users\\boris\\.ssh\\google_compute_engine")
      # Host = VM public IP (Terraform retrieves it automatically)
      host        = google_compute_instance.vm_instance.network_interface[0].access_config[0].nat_ip
    }
  }

}


# # =========================
# # Google Compute Engine VM
# # =========================
# resource "google_compute_instance" "vm_instance" {
#   # Name of the VM
#   name         = "terraform-vm"

#   # Machine type (CPU + RAM)
#   machine_type = "e2-medium"

#   # Zone where the VM will be created
#   zone         = "us-central1-a"

#   # Boot disk configuration
#   boot_disk {
#     initialize_params {
#       # Operating system image
#       image = "debian-cloud/debian-12"
#       # Disk size in GB
#       size  = 10
#     }
#   }

#   # Network configuration
#   network_interface {
#     # Use the default network (already exists in the playground)
#     network       = "default"

#     # Assign a public IP automatically
#     access_config {}
#   }

# }
